spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jpademo?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8

jpa:
#    hibernate:
#      ddl-auto: update
show-sql: true

server:
  port: 8101

# JPA?¥Ø??
