spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpademo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
    username: root
    password: root
#日志文件配置
#输出到控制台 Console 或者文件 File (大小写不敏感)
#默认的日志级别level.root DEBUG
logging:
  appender: File
  path: /data/java/${spring.application.name}
  level:
    root: DEBUG
  file:
    maxFileSize: 100MB
    maxHistory: 5
    totalSizeCap: 1GB